config/routes.rb
Rails.application.routes.draw do
  resources :beneficiaries
  resources :dependents
  devise_for :users
  resources :users
  resources :occupations
  resources :insureds do 
    collection { post :import }
  end
  resources :cooperative_branches
  resources :cooperatives do 
    get :selected, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "cooperatives#index"
end

app/models/dependent.rb
class Dependent < ApplicationRecord
  belongs_to :insured

end

app/controllers/dependents_controller.rb
class DependentsController < ApplicationController
  before_action :set_dependent, only: %i[ show edit update destroy ]

  # GET /dependents or /dependents.json
  def index
    @dependents = Dependent.all
  end

  # GET /dependents/1 or /dependents/1.json
  def show
  end

  # GET /dependents/new
  def new
    @dependent = Dependent.new
  end

  # GET /dependents/1/edit
  def edit
  end

  # POST /dependents or /dependents.json
  def create
    @dependent = Dependent.new(dependent_params)

    respond_to do |format|
      if @dependent.save
        format.html { redirect_to dependent_url(@dependent), notice: "Dependent was successfully created." }
        format.json { render :show, status: :created, location: @dependent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dependents/1 or /dependents/1.json
  def update
    respond_to do |format|
      if @dependent.update(dependent_params)
        format.html { redirect_to dependent_url(@dependent), notice: "Dependent was successfully updated." }
        format.json { render :show, status: :ok, location: @dependent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dependents/1 or /dependents/1.json
  def destroy
    @dependent.destroy

    respond_to do |format|
      format.html { redirect_to dependents_url, notice: "Dependent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dependent
      @dependent = Dependent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dependent_params
      params.require(:dependent).permit(:insured_id, :name, :date_of_birth, :relationship)
    end
end

app/helpers/dependents_helper.rb
module DependentsHelper
end

app/views/dependents/_dependent.html.erb
<div id="<%= dom_id dependent %>">
  <p>
    <strong>Insured:</strong>
    <%= dependent.insured_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= dependent.name %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= dependent.date_of_birth %>
  </p>

  <p>
    <strong>Relationship:</strong>
    <%= dependent.relationship %>
  </p>

</div>

app/views/dependents/_form.html.erb
<%= simple_form_for(@dependent) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :insured %>
    <%= f.input :name %>
    <%= f.input :date_of_birth %>
    <%= f.input :relationship %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dependents/edit.html.erb
<h1>Editing dependent</h1>

<%= render "form", dependent: @dependent %>

<br>

<div>
  <%= link_to "Show this dependent", @dependent %> |
  <%= link_to "Back to dependents", dependents_path %>
</div>

app/views/dependents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dependents</h1>

<div id="dependents">
  <% @dependents.each do |dependent| %>
    <%= render dependent %>
    <p>
      <%= link_to "Show this dependent", dependent %>
    </p>
  <% end %>
</div>

<%= link_to "New dependent", new_dependent_path %>

app/views/dependents/new.html.erb
<h1>New dependent</h1>

<%= render "form", dependent: @dependent %>

<br>

<div>
  <%= link_to "Back to dependents", dependents_path %>
</div>

app/views/dependents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dependent %>

<div>
  <%= link_to "Edit this dependent", edit_dependent_path(@dependent) %> |
  <%= link_to "Back to dependents", dependents_path %>

  <%= button_to "Destroy this dependent", @dependent, method: :delete %>
</div>