config/routes.rb
Rails.application.routes.draw do
  resources :beneficiaries
  resources :dependents
  devise_for :users
  resources :users
  resources :occupations
  resources :insureds do 
    collection { post :import }
  end
  resources :cooperative_branches
  resources :cooperatives do 
    get :selected, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "cooperatives#index"
end

app/models/beneficiary.rb
class Beneficiary < ApplicationRecord
  belongs_to :insured
  
  has_many :insureds, through: :insured_beneficiaries
end

app/controllers/beneficiaries_controller.rb
class BeneficiariesController < ApplicationController
  before_action :set_beneficiary, only: %i[ show edit update destroy ]

  # GET /beneficiaries or /beneficiaries.json
  def index
    @beneficiaries = Beneficiary.all
  end

  # GET /beneficiaries/1 or /beneficiaries/1.json
  def show
  end

  # GET /beneficiaries/new
  def new
    @beneficiary = Beneficiary.new
  end

  # GET /beneficiaries/1/edit
  def edit
  end

  # POST /beneficiaries or /beneficiaries.json
  def create
    @beneficiary = Beneficiary.new(beneficiary_params)

    respond_to do |format|
      if @beneficiary.save
        format.html { redirect_to beneficiary_url(@beneficiary), notice: "Beneficiary was successfully created." }
        format.json { render :show, status: :created, location: @beneficiary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beneficiary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beneficiaries/1 or /beneficiaries/1.json
  def update
    respond_to do |format|
      if @beneficiary.update(beneficiary_params)
        format.html { redirect_to beneficiary_url(@beneficiary), notice: "Beneficiary was successfully updated." }
        format.json { render :show, status: :ok, location: @beneficiary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beneficiary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beneficiaries/1 or /beneficiaries/1.json
  def destroy
    @beneficiary.destroy

    respond_to do |format|
      format.html { redirect_to beneficiaries_url, notice: "Beneficiary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beneficiary
      @beneficiary = Beneficiary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def beneficiary_params
      params.require(:beneficiary).permit(:insured_id, :name, :date_of_birth, :relationship)
    end
end

app/helpers/beneficiaries_helper.rb
module BeneficiariesHelper
end

app/views/beneficiaries/_beneficiary.html.erb
<div id="<%= dom_id beneficiary %>">
  <p>
    <strong>Insured:</strong>
    <%= beneficiary.insured_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= beneficiary.name %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= beneficiary.date_of_birth %>
  </p>

  <p>
    <strong>Relationship:</strong>
    <%= beneficiary.relationship %>
  </p>

</div>

app/views/beneficiaries/_form.html.erb
<%= simple_form_for(@beneficiary) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :insured %>
    <%= f.input :name %>
    <%= f.input :date_of_birth %>
    <%= f.input :relationship %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/beneficiaries/edit.html.erb
<h1>Editing beneficiary</h1>

<%= render "form", beneficiary: @beneficiary %>

<br>

<div>
  <%= link_to "Show this beneficiary", @beneficiary %> |
  <%= link_to "Back to beneficiaries", beneficiaries_path %>
</div>

app/views/beneficiaries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Beneficiaries</h1>

<div id="beneficiaries">
  <% @beneficiaries.each do |beneficiary| %>
    <%= render beneficiary %>
    <p>
      <%= link_to "Show this beneficiary", beneficiary %>
    </p>
  <% end %>
</div>

<%= link_to "New beneficiary", new_beneficiary_path %>

app/views/beneficiaries/new.html.erb
<h1>New beneficiary</h1>

<%= render "form", beneficiary: @beneficiary %>

<br>

<div>
  <%= link_to "Back to beneficiaries", beneficiaries_path %>
</div>

app/views/beneficiaries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @beneficiary %>

<div>
  <%= link_to "Edit this beneficiary", edit_beneficiary_path(@beneficiary) %> |
  <%= link_to "Back to beneficiaries", beneficiaries_path %>

  <%= button_to "Destroy this beneficiary", @beneficiary, method: :delete %>
</div>