config/routes.rb
Rails.application.routes.draw do
  resources :beneficiaries
  resources :dependents
  devise_for :users
  resources :users
  resources :occupations
  resources :insureds do 
    collection { post :import }
  end
  resources :cooperative_branches
  resources :cooperatives do 
    get :selected, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "cooperatives#index"
end

app/models/cooperative_branch.rb
class CooperativeBranch < ApplicationRecord
  belongs_to :cooperative

  def to_s 
    name
  end
end

app/controllers/cooperative_branches_controller.rb
class CooperativeBranchesController < ApplicationController
  before_action :set_cooperative_branch, only: %i[ show edit update destroy ]

  # GET /cooperative_branches or /cooperative_branches.json
  def index
    @cooperative_branches = CooperativeBranch.all
  end

  # GET /cooperative_branches/1 or /cooperative_branches/1.json
  def show
  end

  # GET /cooperative_branches/new
  def new
    @cooperative_branch = CooperativeBranch.new
  end

  # GET /cooperative_branches/1/edit
  def edit
  end

  # POST /cooperative_branches or /cooperative_branches.json
  def create
    @cooperative_branch = CooperativeBranch.new(cooperative_branch_params)

    respond_to do |format|
      if @cooperative_branch.save
        format.html { redirect_to cooperative_branch_url(@cooperative_branch), notice: "Cooperative branch was successfully created." }
        format.json { render :show, status: :created, location: @cooperative_branch }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cooperative_branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cooperative_branches/1 or /cooperative_branches/1.json
  def update
    respond_to do |format|
      if @cooperative_branch.update(cooperative_branch_params)
        format.html { redirect_to cooperative_branch_url(@cooperative_branch), notice: "Cooperative branch was successfully updated." }
        format.json { render :show, status: :ok, location: @cooperative_branch }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cooperative_branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cooperative_branches/1 or /cooperative_branches/1.json
  def destroy
    @cooperative_branch.destroy

    respond_to do |format|
      format.html { redirect_to cooperative_branches_url, notice: "Cooperative branch was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cooperative_branch
      @cooperative_branch = CooperativeBranch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cooperative_branch_params
      params.require(:cooperative_branch).permit(:cooperative_id, :name, :address)
    end
end

app/views/cooperative_branches/_cooperative_branch.html.erb
<div id="<%= dom_id cooperative_branch %>">
  <p>
    <strong>Cooperative:</strong>
    <%= cooperative_branch.cooperative_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= cooperative_branch.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= cooperative_branch.address %>
  </p>

</div>

app/views/cooperative_branches/_form.html.erb
<%= simple_form_for(@cooperative_branch) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :cooperative %>
    <%= f.input :name %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cooperative_branches/edit.html.erb
<div class="container">
  <h1>Editing cooperative branch</h1>

  <%= render "form", cooperative_branch: @cooperative_branch %>

  <br>

  <div>
    <%= link_to "Show this cooperative branch", @cooperative_branch %> |
    <%= link_to "Back to cooperative branches", cooperative_branches_path %>
  </div>
</div>

app/views/cooperative_branches/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <h1>Cooperative branches</h1>

  <table class="table table-stripped table-hover">
      <thead>
        <tr>
          <th>Cooperative</th>
          <th>Branch</th>
          <th>Address</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
      <% @cooperative_branches.each do |cb| %>
        <tr class="text-nowrap">
          <td><%= cb.cooperative.name %></td>
          <td><%= cb.name %></td>
          <td><%= cb.address %></td>
          <td><%= link_to 'Edit', edit_cooperative_branch_path(cb), class: "btn btn-outline-info" %> <%= link_to 'Delete', cooperative_branch_path(cb), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger" %></td>
        </tr>
      </tbody>
      <% end %>
    </table>

  <%= link_to "New cooperative branch", new_cooperative_branch_path, class: "btn btn-outline-success" %>
</div>

app/views/cooperative_branches/new.html.erb
<div class="container">
  <h1>New cooperative branch</h1>

  <%= render "form", cooperative_branch: @cooperative_branch %>

  <br>

  <div>
    <%= link_to "Back to cooperative branches", cooperative_branches_path %>
  </div>
</div>

app/views/cooperative_branches/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @cooperative_branch %>

  <div>
    <%= link_to "Edit this cooperative branch", edit_cooperative_branch_path(@cooperative_branch) %> |
    <%= link_to "Back to cooperative branches", cooperative_branches_path %>

    <%= button_to "Destroy this cooperative branch", @cooperative_branch, method: :delete %>
  </div>
</div>