config/routes.rb
Rails.application.routes.draw do
  resources :beneficiaries
  resources :dependents
  devise_for :users
  resources :users
  resources :occupations
  resources :insureds do 
    collection { post :import }
  end
  resources :cooperative_branches
  resources :cooperatives do 
    get :selected, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "cooperatives#index"
end

app/models/cooperative.rb
class Cooperative < ApplicationRecord

	def to_s 
		name
	end 
end

app/controllers/cooperatives_controller.rb
class CooperativesController < ApplicationController
  before_action :set_cooperative, only: %i[ show edit update destroy ]

  # GET /cooperatives or /cooperatives.json
  def index
    @cooperatives = Cooperative.all
  end

  # GET /cooperatives/1 or /cooperatives/1.json
  def show
  end

  def selected 
    @target = params[:target] 
    @branches = CooperativeBranch.where(cooperative_id: params[:id])
    respond_to do |format|
      format.turbo_stream
    end
  end

  # GET /cooperatives/new
  def new
    @cooperative = Cooperative.new
  end

  # GET /cooperatives/1/edit
  def edit
  end

  # POST /cooperatives or /cooperatives.json
  def create
    @cooperative = Cooperative.new(cooperative_params)

    respond_to do |format|
      if @cooperative.save
        format.html { redirect_to cooperative_url(@cooperative), notice: "Cooperative was successfully created." }
        format.json { render :show, status: :created, location: @cooperative }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cooperative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cooperatives/1 or /cooperatives/1.json
  def update
    respond_to do |format|
      if @cooperative.update(cooperative_params)
        format.html { redirect_to cooperative_url(@cooperative), notice: "Cooperative was successfully updated." }
        format.json { render :show, status: :ok, location: @cooperative }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cooperative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cooperatives/1 or /cooperatives/1.json
  def destroy
    @cooperative.destroy

    respond_to do |format|
      format.html { redirect_to cooperatives_url, notice: "Cooperative was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cooperative
      @cooperative = Cooperative.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cooperative_params
      params.require(:cooperative).permit(:name, :address, :abbreviation, :region)
    end
end

app/views/cooperatives/_cooperative.html.erb
<div id="<%= dom_id cooperative %>">
  <p>
    <strong>Name:</strong>
    <%= cooperative.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= cooperative.address %>
  </p>

  <p>
    <strong>Abbreviation:</strong>
    <%= cooperative.abbreviation %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= cooperative.region %>
  </p>

</div>

app/views/cooperatives/_form.html.erb
<%= simple_form_for(@cooperative) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :abbreviation %>
    <%= f.input :region %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cooperatives/edit.html.erb
<div class="container">
  <h1>Editing cooperative</h1>

  <%= render "form", cooperative: @cooperative %>

  <br>

  <div>
    <%= link_to "Show this cooperative", @cooperative %> |
    <%= link_to "Back to cooperatives", cooperatives_path %>
  </div>
</div>

app/views/cooperatives/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <h1>Cooperatives</h1>

  <table class="table table-stripped table-hover">
      <thead>
        <tr class="text-nowrap">
          <th>Name</th>
          <th>Address</th>
          <th>Abbreviation</th>
          <th>Region</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
      <% @cooperatives.each do |cooperative| %>
        <tr class="text-nowrap">
          <td><%= cooperative.name%></td>
          <td><%= cooperative.address%></td>
          <td><%= cooperative.abbreviation%></td>
          <td><%= cooperative.region%></td>
          <td><%= link_to 'Edit', edit_cooperative_path(cooperative), class: "btn btn-outline-info" %> <%= link_to 'Delete', cooperative_path(cooperative), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger" %></td>
        </tr>
      </tbody>
      <% end %>
    </table>

  <%= link_to "New cooperative", new_cooperative_path, class: "btn btn-outline-success" %>
</div>

app/views/cooperatives/new.html.erb
<div class="container">
  <h1>New cooperative</h1>

  <%= render "form", cooperative: @cooperative %>

  <br>

  <div>
    <%= link_to "Back to cooperatives", cooperatives_path %>
  </div>
</div>

app/views/cooperatives/selected.turbo_stream.erb
<%= turbo_stream.update @target do %>
    <%= @branches.each do |branch| %>
        <%= content_tag :option, branch.name, value: branch.id %>
    <% end %>
<% end %>

app/views/cooperatives/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @cooperative %>

  <div>
    <%= link_to "Edit this cooperative", edit_cooperative_path(@cooperative) %> |
    <%= link_to "Back to cooperatives", cooperatives_path %>

    <%= button_to "Destroy this cooperative", @cooperative, method: :delete %>
  </div>
</div>